import type { NatsFlowScenario } from '../types';

const ROUTE_COLOR = '#1e40af';
const LEAF_COLOR = '#9333ea';
const CLIENT_COLOR = '#3b82f6';

export const mixedTopologyScenario: NatsFlowScenario = {
  description: 'All together: a cluster in the center, leaf nodes extending the namespace to clients at the edge.',
  nodes: [
    {
      id: 'tl-c1',
      type: 'publisher',
      position: { x: 40, y: 60 },
      data: { label: 'Client' },
    },
    {
      id: 'tl-c2',
      type: 'publisher',
      position: { x: 40, y: 180 },
      data: { label: 'Client' },
    },
    {
      id: 'tl-c3',
      type: 'publisher',
      position: { x: 40, y: 300 },
      data: { label: 'Client' },
    },
    {
      id: 'top-leaf',
      type: 'server',
      position: { x: 280, y: 180 },
      data: { label: 'Leaf Node' },
    },
    {
      id: 'bl-c1',
      type: 'publisher',
      position: { x: 40, y: 500 },
      data: { label: 'Client' },
    },
    {
      id: 'bl-c2',
      type: 'publisher',
      position: { x: 40, y: 620 },
      data: { label: 'Client' },
    },
    {
      id: 'bl-c3',
      type: 'publisher',
      position: { x: 40, y: 740 },
      data: { label: 'Client' },
    },
    {
      id: 'bot-leaf',
      type: 'server',
      position: { x: 280, y: 620 },
      data: { label: 'Leaf Node' },
    },
    {
      id: 'cluster-A',
      type: 'server',
      position: { x: 600, y: 400 },
      data: { label: 'NATS' },
    },
    {
      id: 'cluster-B',
      type: 'server',
      position: { x: 860, y: 220 },
      data: { label: 'NATS' },
    },
    {
      id: 'cluster-C',
      type: 'server',
      position: { x: 1060, y: 460 },
      data: { label: 'NATS' },
    },
    {
      id: 'B-client',
      type: 'publisher',
      position: { x: 860, y: 60 },
      data: { label: 'Client' },
    },
    {
      id: 'A-client',
      type: 'subscriber',
      position: { x: 600, y: 620 },
      data: { label: 'Client' },
    },
    {
      id: 'C-client',
      type: 'subscriber',
      position: { x: 1060, y: 680 },
      data: { label: 'Client' },
    },
  ],
  edges: [
    {
      id: 'tlc1-leaf',
      source: 'tl-c1',
      target: 'top-leaf',
      type: 'animated',
      data: { color: CLIENT_COLOR, animated: false, straight: true },
    },
    {
      id: 'tlc2-leaf',
      source: 'tl-c2',
      target: 'top-leaf',
      type: 'animated',
      data: { color: CLIENT_COLOR, animated: false, straight: true },
    },
    {
      id: 'tlc3-leaf',
      source: 'tl-c3',
      target: 'top-leaf',
      type: 'animated',
      data: { color: CLIENT_COLOR, animated: false, straight: true },
    },
    {
      id: 'blc1-leaf',
      source: 'bl-c1',
      target: 'bot-leaf',
      type: 'animated',
      data: { color: CLIENT_COLOR, animated: false, straight: true },
    },
    {
      id: 'blc2-leaf',
      source: 'bl-c2',
      target: 'bot-leaf',
      type: 'animated',
      data: { color: CLIENT_COLOR, animated: false, straight: true },
    },
    {
      id: 'blc3-leaf',
      source: 'bl-c3',
      target: 'bot-leaf',
      type: 'animated',
      data: { color: CLIENT_COLOR, animated: false, straight: true },
    },
    {
      id: 'top-leaf-cluster',
      source: 'top-leaf',
      target: 'cluster-A',
      type: 'animated',
      data: { color: LEAF_COLOR, animated: false, straight: true, label: 'leaf' },
    },
    {
      id: 'bot-leaf-cluster',
      source: 'bot-leaf',
      target: 'cluster-A',
      type: 'animated',
      data: { color: LEAF_COLOR, animated: false, straight: true, label: 'leaf' },
    },
    {
      id: 'A-B',
      source: 'cluster-A',
      target: 'cluster-B',
      type: 'animated',
      data: { color: ROUTE_COLOR, animated: false, straight: true },
    },
    {
      id: 'B-C',
      source: 'cluster-B',
      target: 'cluster-C',
      type: 'animated',
      data: { color: ROUTE_COLOR, animated: false, straight: true },
    },
    {
      id: 'A-C',
      source: 'cluster-A',
      target: 'cluster-C',
      type: 'animated',
      data: { color: ROUTE_COLOR, animated: false, straight: true },
    },
    {
      id: 'Bclient-B',
      source: 'B-client',
      target: 'cluster-B',
      type: 'animated',
      data: { color: CLIENT_COLOR, animated: false, straight: true },
    },
    {
      id: 'A-Aclient',
      source: 'cluster-A',
      target: 'A-client',
      type: 'animated',
      data: { color: CLIENT_COLOR, animated: false, straight: true },
    },
    {
      id: 'C-Cclient',
      source: 'cluster-C',
      target: 'C-client',
      type: 'animated',
      data: { color: CLIENT_COLOR, animated: false, straight: true },
    },
  ],
};
